name: Security Scan

on:
  workflow_dispatch:

jobs:
  dast-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Start API
      run: |
        docker-compose up -d
        sleep 10
        
    - name: OWASP ZAP Scan
      uses: zaproxy/action-full-scan@v0.9.0
      with:
        target: 'http://localhost:5000'
        rules_file_name: '.zap/rules.tsv'
        
    - name: Stop API
      run: docker-compose down